server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=MockProject_072024_Nhom3
    username: sa
    password: VietDoan123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html